bbaegi-six/dondothat-client

src/App.vue
#22 
스크롤바 가리기 스타일 설정했음
전체 배경색 f2f2f2로 스타일 설정했음
=> fix: 전역 설정 수정 #22

src/components/chat/ChatMessage.vue, src/pages/chat/Chat.vue, src/pages/chat/NoChat.vue
closed #20 
- 참여중인 채팅방 없을 때 보여줄 페이지 (default 페이지)
- 채팅 페이지 배경색 수정(#2F2F2F)
- 채팅 페이지 헤더 수정
<p align="center">
</p>
=> [FIX] 채팅 페이지 수정

src/App.vue, src/components/BaseCard.vue, src/components/Square.vue, src/components/Typography.vue
#25 
- 은행선택 및 마이페이지에 쓰이는 정사각형 모양의 컴포넌트 추가
- 마이페이지에 반복적으로 쓰이는 글자 컴포넌트 추가
- 기존 BaseCard색상을 피그마 반영하여 수정
=> [FEAT] 기본 컴포넌트 추가

.gitignore, netlify.toml
#28 fix 프론트 배포 실시간 반영
netlify.toml 파일 생성
=> feat: #28 netlify.toml 파일 생성

src/App.vue, src/components/profile/Challenge.vue, src/pages/profile/Completed.vue, src/pages/profile/MyChallenge.vue, src/pages/profile/Profile.vue, src/router/index.js, src/stores/profile.js
#36 
마이페이지 내 성공한/실패한 챌린지 목록 페이지를 구현하였다
일단은 pinia를 사용해 목데이터로 구현함
=> [FEAT] 마이챌린지 페이지 구현

.env, src/components/chat/ChatMessage.vue, src/pages/chat/Chat.vue, src/router/index.js, src/services/chatApi.js, src/stores/chat.js
closed #58 
- WebSocket 연결 안정성 개선 (타임아웃, 에러 처리)
- 메시지 수신/전송 로직 강화 (상세 로깅, 낙관적 업데이트)
- 시간 형식 처리 개선 (배열 형태 timestamp 지원)
- 사용자 정보 관리 개선 (ID 동기화, 쿼리 파라미터 감지)
- UI 상태 관리 개선 (로딩 상태, 에러 처리)
- 디버깅 로깅 추가 (메시지 소유자 확인, 사용자 정보)
- 중복 코드 정리 (chatApi.js WebSocket 로직 제거)
해결해야 할 문제:
- 채팅 UI 로딩 상태 무한 대기
- 시간 표시 오류
- 다른 사용자 메시지가 내 메시지로 표시되는 문제
- WebSocket 연결 불안정성
=> [FEAT] 이전 메시지 불러오기

src/pages/auth/Login.vue, src/pages/auth/Register.vue, src/stores/auth.js
#68 
- 회원가입 폼에 사용자 나이 입력칸 추가 (정수만 입력 가능)
- 회원가입시, api 요청에 나이 필드(age) 추가
- 나이 입력칸 추가
- 회원가입 요청 페이로드
관련 백엔드 작업
https://github.com/bbaegi-six/dondothat-server/pull/121
=> [FEAT] 회원가입 폼에 사용자 나이 입력칸 추가

src/pages/chat/Chat.vue, src/services/chatApi.js, src/stores/chat.js, src/utils/api.js
closed #69 
- 채팅 페이지 로딩 완료
- `chatApi.js`: API 경로 수정
- `Chat.vue`: JWT 기반 사용자 정보 처리
**추후 수정사항**
- 메시지 시간 표시 수정(보낸 시각 표시, 날짜별 시스템 메시지)
- 시스템 메시지 표시 제거 (참여한 이후의 메시지입니다)
- 메시지 입력창 화면 하단에 고정
- 채팅방 상단에 필요없는 부분 삭제 필요
- 프론트 페이지에서 메시지 두 번 보이는 버그 수정
=> [FIX] 채팅 페이지 입장 오류 수정

src/pages/challenge/Challenge.vue, src/pages/challenge/ChallengeFailed.vue, src/pages/challenge/ChallengeFlow.vue, src/pages/challenge/ChallengeLoading.vue, src/pages/challenge/ChallengeProgress.vue, src/pages/challenge/ChallengeSelection.vue, src/router/index.js, src/stores/challenge.js, src/utils/api.js
closed #47
- ChallengeFailed.vue구현
- ChallengeFlow.vue 수정
- Challenge.js 추가
- Challange.vue 버튼 사라진 오류 수정
=> [FEAT] 챌린지 실패 페이지 구현

src/components/layout/Header.vue, src/pages/expenses/ExpenseEdit.vue
closed #66 
삭제 버튼이 눌리지 않는 오류를 수정했습니다.
헤더 밑의 구분선 배치를 수정했습니다.
=> [BUG] 소비내역 삭제 오류, 구분선 배치 수정

src/components/chat/ChatMessage.vue, src/components/layout/Header.vue, src/pages/chat/Chat.vue, src/stores/chat.js
closed #83 
- 시스템 메시지로 날짜 구분 
- 공통 `Header.vue` 적용
=> [FIX] 채팅 페이지 시간, 헤더 수정

src/utils/api.js
#91 리다이렉트 주소 변경
api url netlify 설정으로 변경
=> [FIX] API url 설정 변경

src/components/expenses/TransactionCard.vue, src/pages/expenses/ExpenseEdit.vue, src/stores/expenses.js
#96 수입일 경우 금액 표시 변경
- 지출내역에 지출만 표시
-  추가 삭제 시 수입 버튼 is-show false로 변경
=> [FIX]  지출 내역에 지출만 표시

src/components/chat/ChatChecking.vue, src/components/chat/ChatError.vue, src/components/chat/ChatInput.vue, src/components/chat/ChatLoading.vue, src/components/chat/ChatMessages.vue, src/components/chat/ChatStatus.vue, src/pages/chat/Chat.vue
closed #89 
- 기존의 `Chat.vue`에 있던 코드들을 컴포넌트로 분리
- 채팅 입력창 배경을 채팅창의 배경과 통일시키고 여백제거, 구분선 삭제함
- 채팅 입력창을 하단바 바로 위에 고정
- 입력창 위의 공간만 채팅 메시지가 보이도록 수정
- 시스템 메시지(입장 메시지)가 일반 메시지 밑으로 밀리는 버그
- 채팅 입장 시 가장 오래된 메시지가 아닌 최신 메시지가 보이도록 수정 필요
=> [FIX] 채팅 입력창 버그 수정

src/pages/home/Home.vue
#101 
- 메인페이지 진입시 사용자의 savingConnected 필드 확인
- true -> 지금까지 아낀 금액 출력 (데이터 연동은 안됨)
- false -> 저금통 연결하기 출력
=> [FEAT] 메인페이지 저금통 여부 조건부 렌더링

src/components/layout/Header.vue, src/pages/account/steps/Step5Complete.vue, src/pages/expenses/Expenses.vue, src/pages/home/Home.vue, src/services/expensesService.js, src/stores/expenses.js
closed #98 
자산연동 후 데이터 로딩되게 코드를 수정. 새로고침 추가.
=> [REFACTOR] 내역 페이지에 새로고침 버튼 및 자산연동 후 데이터 로딩

src/components/layout/Nav.vue
#107 
- 네브바 아이콘 활성화를 구분하였습니다.
- 활성화 색상 : ff5555 (Brand color)
=> [FEAT] 네브바 아이콘 활성화 여부 표시

src/components/layout/Nav.vue, src/pages/expenses/ExpenseEdit.vue, src/pages/expenses/Expenses.vue, src/stores/expenses.js
closed: #112 
추가 버튼 위치 수정, 내역 오류 수정, 날짜 변경 수정
=> [REFACTOR] 내역 추가 버튼 수정, 날짜 변경 수정

src/pages/account/steps/Step2BankSelect.vue, src/pages/account/steps/Step3AccountForm.vue, src/pages/account/steps/Step4Processing.vue, src/pages/account/steps/Step5Complete.vue, src/pages/challenge/Challenge.vue, src/utils/api.js
#122 저금통 연결 여부 관련 구현 
- 챌린지 시작시 저금통 연결 페이지 로직 구현
- saving connected 코드 수정
- asset과 saving connected 로컬 반영으로 추가
- Asset에서 enter로 이동 구현
=> [FEAT] 챌린지 시작시 저금통 연결 페이지 구현

src/main.js, src/pages/challenge/Challenge.vue, src/pages/challenge/ChallengeFailed.vue, src/pages/challenge/ChallengeProgress.vue, src/pages/home/Home.vue, src/services/challengeService.js, src/stores/challenge.js
#128 
- 메인페이지에 참여 중인 챌린지 정보 출력
- 로그인 후 /progress 호출 -> store에 저장 -> 불러와서 메인페이지에서 출력
- 챌린지 현황 페이지에서 아이콘 크기 조정
=> [FEAT] 챌린지 참여 정보 출력

src/pages/challenge/ChallengeFailed.vue, src/services/challengeService.js
#133 챌린지 실패 백엔드 연동
챌린지 실패시 소비내역 호출 연결
=> [FEAT] 챌린지 실패시 소비내역 호출 연결

src/pages/challenge/ModalSecond.vue, src/utils/api.js
closed #135 
- 마이페이지 API 사용: /mypage/tier에서 실제 tierName 가져옴
- 콘페티 효과 추가
=> [FEAT] 티어 승급 모달 구현 완료

src/pages/challenge/ChallengeProgress.vue, src/pages/challenge/ModalFirst.vue, src/services/savingService.js, src/stores/saving.js
#137 
- 저금통 페이지에서 챌린지별 아낀금액 계산이 안뜨는 문제
- 챌린지에서 저금하기 눌렀을때 저금이 안되는 문제
- 저금하기 눌렀을때 숫자가 NaN이라고 뜨는 문제
=> [FIX] 저금 관련 여러 문제 해결

src/pages/challenge/ChallengeProgress.vue, src/pages/expenses/Expenses.vue, src/pages/home/Home.vue
=> [FEAT] 메인페이지에 저금 연동 #141

src/components/modals/SavedAmountInfoModal.vue, src/pages/challenge/ChallengeProgress.vue
closed #146 
- `ChallengeProgress.vue` 에 아낀 금액 산정 모달 추가
- `/src/components/modals/SavedAmountInfoModal.vue`
=> [FEAT] 아낀 금액 산정 모달

src/components/layout/Header.vue, src/pages/expenses/Expenses.vue, src/pages/profile/Profile.vue
#157 
- 소비내역 페이지, 마이페이지에서 헤더 구분선 제거
- 새로고침 아이콘 배경 제거
=> [REFACTOR] UI 일부 수정

src/pages/challenge/ModalThird.vue, src/pages/home/Home.vue
closed #167 
- **순차 실행 -> 병렬 처리**: 3개 독립적인 API를 Promise.allSettled로 동시 실행
- **에러 처리** : 개별 API 실패 시에도 다른 데이터 정상 표시
- **동적 배열 구성**: 로그인 상태에 따른 조건부 API 호출
- **Home.vue**: onBeforeUnmount 훅 추가하여 Chart.js 인스턴스 정리
- **ModalThird.vue**: v-for key를 index 기반에서 unique identifier로 변경
=> [Refactor] Home 화면 API 병렬 처리, 메모리 누수 해결 및 렌더링 성능 개선

src/components/charts/ExpenseChart.vue, src/components/sections/ChallengeSection.vue, src/components/sections/ExpenseSummary.vue, src/components/sections/SavingAccountSection.vue, src/pages/expenses/Expenses.vue, src/pages/home/Home.vue, src/stores/challenge.js, src/utils/savingCache.js
closed #172 
Chart.js 중복 생성 방지, watch 조건 개선
컴포넌트 분할
로직 최적화: computed 함수들 캐싱 개선, 중복 로직 제거
번들 최적화: Chart.js 트리 셰이킹, 필요한 컴포넌트만 import
API 최적화: 비필수 API 지연 로딩, 캐싱 전략 개선
저금통 데이터 캐싱: 평상시 캐시된 데이터로 즉시 표시
내역 새로고침 버튼: 내역페이지의 새로고침 버튼으로 저금통 API도 동시 호출
자동 갱신: 챌린지 완료 시에만 캐시 무효화 및 자동 갱신
스마트 캐싱: 영구 캐시 + 이벤트 기반 무효화
현재 체감상으로는 개선이 많이 됐지만 라이트하우스 점수는 좋지 않음. LCP가 너무 높음
Chart.js 개선이 필요
=> [REFACTOR] 홈페이지 화면 최적화, 저금통 캐싱으로 로딩 성능 최적화

src/components/chat/ChatInput.vue, src/components/chat/ChatMessage.vue, src/components/chat/ChatMessages.vue, src/pages/chat/Chat.vue, src/pages/chat/NoChat.vue, src/stores/chat.js
=> [FIX] 채팅 페이지 반응형 수정
